version: '3.8'

services:
  # Databases
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: streamforge
      POSTGRES_USER: streamforge
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - streamforge-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streamforge-network

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_GATEWAY_SERVER_PORT=8080
      - API_GATEWAY_DATABASE_HOST=postgres
      - API_GATEWAY_DATABASE_USER=streamforge
      - API_GATEWAY_DATABASE_PASSWORD=password123
      - API_GATEWAY_DATABASE_DBNAME=streamforge
      - API_GATEWAY_REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - streamforge-network

  # Stream Ingestion Service
  stream-ingestion:
    build:
      context: .
      dockerfile: services/stream-ingestion/Dockerfile
    ports:
      - "8081:8081"
      - "1935:1935"  # RTMP port
    environment:
      - STREAM_INGESTION_SERVER_PORT=8081
      - STREAM_INGESTION_STREAM_RTMP_PORT=1935
      - STREAM_INGESTION_REDIS_HOST=redis
    volumes:
      - stream_data:/tmp/streams
    depends_on:
      - redis
    networks:
      - streamforge-network

  # Stream Processing Service
  stream-processing:
    build:
      context: .
      dockerfile: services/stream-processing/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - STREAM_PROCESSING_SERVER_PORT=8082
      - STREAM_PROCESSING_STREAM_HLS_PATH=/tmp/hls
      - STREAM_PROCESSING_STREAM_DASH_PATH=/tmp/dash
      - STREAM_PROCESSING_REDIS_HOST=redis
    volumes:
      - stream_data:/tmp/streams
      - hls_data:/tmp/hls
      - dash_data:/tmp/dash
    depends_on:
      - redis
      - stream-ingestion
    networks:
      - streamforge-network

  # Stream Distribution Service
  stream-distribution:
    build:
      context: .
      dockerfile: services/stream-distribution/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - STREAM_DISTRIBUTION_SERVER_PORT=8083
      - STREAM_DISTRIBUTION_STREAM_HLS_PATH=/tmp/hls
      - STREAM_DISTRIBUTION_STREAM_DASH_PATH=/tmp/dash
      - STREAM_DISTRIBUTION_REDIS_HOST=redis
    volumes:
      - hls_data:/tmp/hls
      - dash_data:/tmp/dash
    depends_on:
      - redis
      - stream-processing
    networks:
      - streamforge-network

  # User Management Service
  user-management:
    build:
      context: .
      dockerfile: services/user-management/Dockerfile
    ports:
      - "8084:8084"
    environment:
      - USER_MANAGEMENT_SERVER_PORT=8084
      - USER_MANAGEMENT_DATABASE_HOST=postgres
      - USER_MANAGEMENT_DATABASE_USER=streamforge
      - USER_MANAGEMENT_DATABASE_PASSWORD=password123
      - USER_MANAGEMENT_DATABASE_DBNAME=streamforge
      - USER_MANAGEMENT_AUTH_JWT_SECRET=your-super-secret-jwt-key
      - USER_MANAGEMENT_REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - streamforge-network

  # Stream Metadata Service
  stream-metadata:
    build:
      context: .
      dockerfile: services/stream-metadata/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - STREAM_METADATA_SERVER_PORT=8085
      - STREAM_METADATA_DATABASE_HOST=postgres
      - STREAM_METADATA_DATABASE_USER=streamforge
      - STREAM_METADATA_DATABASE_PASSWORD=password123
      - STREAM_METADATA_DATABASE_DBNAME=streamforge
      - STREAM_METADATA_REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - streamforge-network

  # Notification Service
  notification:
    build:
      context: .
      dockerfile: services/notification/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - NOTIFICATION_SERVER_PORT=8086
      - NOTIFICATION_REDIS_HOST=redis
      - NOTIFICATION_DATABASE_HOST=postgres
      - NOTIFICATION_DATABASE_USER=streamforge
      - NOTIFICATION_DATABASE_PASSWORD=password123
      - NOTIFICATION_DATABASE_DBNAME=streamforge
    depends_on:
      - postgres
      - redis
    networks:
      - streamforge-network

  # Analytics Service
  analytics:
    build:
      context: .
      dockerfile: services/analytics/Dockerfile
    ports:
      - "8087:8087"
    environment:
      - ANALYTICS_SERVER_PORT=8087
      - ANALYTICS_DATABASE_HOST=postgres
      - ANALYTICS_DATABASE_USER=streamforge
      - ANALYTICS_DATABASE_PASSWORD=password123
      - ANALYTICS_DATABASE_DBNAME=streamforge
      - ANALYTICS_REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - streamforge-network

  # Web Dashboard (Optional)
  web-dashboard:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - api-gateway
    networks:
      - streamforge-network

volumes:
  postgres_data:
  redis_data:
  stream_data:
  hls_data:
  dash_data:

networks:
  streamforge-network:
    driver: bridge 